### ISSUE TITLE
Error: osdmain.elf is Not Found

### ISSUE THREAD

**Issue by Jay-Jay-OPL** [AKuHAK/uLaunchELF#24]
We have a member at PS2-HOME reporting a possible bug when using wLE with FHDB.  http://www.ps2-home.com/forum/viewtopic.php?f=16&t=6519

When he wants to setup a shortcut button on wLE for the following path: `MISC/OSDSYS`  -- He gets this error: `mc:/BAEXEC-SYSTEM/osdmain.elf is Not Found.`

So it seems the issue is that wLE is looking for it under MC and not under his HDD (FHDB) setup.

Is this a known issue or a new bug for FHDB users and wLE?

**Comment by sp193** [comment]
LaunchELF does not support booting KELFs on the HDD. This has nothing to do with other projects, like FHDB.

To boot a KELF on a device that the boot ROM does not support, we need to implement additional logic to boot an encrypted file from LaunchELF's embedded ELF loader, rather than with the LoadExecPS2 syscall (which is used for booting updates from memory cards). LaunchELF can do it with the right changes, but is currently just not meant to do it.

A long time ago, that option (MISC/OSDSYS) was meant for people to be able to try booting a KELF from memory card. However, the natural way to do it, is to boot to the browser (MISC/PS2Browser) and let it locate and boot the update (the KELF).

The update file on the HDD was also meant to be booted from the MBR program, which is booted by the browser at boot. So the proper way to boot an update on the HDD, might be to boot the MBR program instead of booting a specific file.

Normal users do not need this function, so I see no reason to update it. But we can keep it there, since it is already there and works fine. Why can't he just boot into the browser and let it boot whatever update that is found?

"OSDSYS" refers to the browser, regardless of where you actually boot it from (does not specifically refer to an update on either the HDD or memory card). I guess this option got its name because homebrew developers back then already knew that the browser in ROM was called "OSDSYS" by filename.

In FMCB/FHDB, "OSDSYS" just means "do nothing and resume boot to browser".
