### ISSUE TITLE
FTP and PS2NET -- can't see USB HDD until...

### ISSUE THREAD

**Issue by Jay-Jay-OPL** [AKuHAK/uLaunchELF#25]
@SP193, just testing: **_Update 2018/11/03: v0.984 (FMCB v1.965) re-released_**.  Which includes: **_wLaunchELF_v4.43a (Build-9c18290-2018-11-03)_** 

I think something changed in the way now that the USB HDD module loads via FTP using wLE's PS2NET.

Before, when I would run it, through my FTP client I can see both the MC's and also the USB HDD (mass) connected to the PS2 unit.

Now with all the latest changes, it will not.  It will only see the MCs, but not the USB HDD.  It will only see it if I navigate (using the File Browser) to the mass directory, then when I refresh my FTP client, I can finally see the USB HDD folder contents (mass).

Is this a bug?  If not, could you make PS2DEV automatically scan and run the USB MODULE, this way we don't need to do so many steps in order for our FTP clients to see the USB HDD?

**Comment by sp193** [comment]
It was always like that. Most of the add-on drivers would never be loaded, until the user explicitly chooses to access such devices. That was the methodology of the uLaunchELF developers.

But because you asked and it does make sense to load some drivers at boot, I have changed this with commit bddf737. Most people will probably try to access mass: anyway.

**Comment by Jay-Jay-OPL** [comment]
@sp193 , you think you can also do that for **Internal HDD** users for PS2NET?  

We have a case that when a user runs PS2NET, he can't see the Internal HDD listed on his FTP client until he navigates to the internal HDD using wLE and (I guess) activates the Internal HDD to be listed on his PS2 unit.

Here is the topic: http://www.ps2-home.com/forum/viewtopic.php?f=16&t=7796

In other words for PS2NET have the ability to activate all connected devices that it can browse once activated.

**Comment by sp193** [comment]
Hi,

If I do that, another group will surely complain...
"Why leave my HDD on"
"It now takes time to shut down my PS2"
"Add an option"
"That made LaunchELF start slower"
etc.

Unlike newer consoles and the PC, the HDD unit is never activated by default. So whenever the necessary modules are loaded, there will be some delay as the HDD spins up. There is just no quick way to determine whether a device is connected.

I can't please everybody. This was the design of LaunchELF since a very long time ago, so it's not like this is totally unexpected.

**Comment by Jay-Jay-OPL** [comment]
@sp193 thanks for your reply, it is always appreciated...

Sorry, but I need a bit of clarification from you.

Earlier in this ticket you stated the following:

> It was always like that. Most of the add-on drivers **_would never be loaded_**, until the user explicitly chooses to access such devices. That was the methodology of the uLaunchELF developers.

And then now your recent reply you state the following:

> This was the design of LaunchELF since a very long time ago, so it's **_not like this is totally unexpected_**.

I've read it a few times, but I just want you to clear that up for me... (read below to learn what confuses me from what you stated above)

Now I'm not sure if you use FTP as much as I do, but I recall a time with older versions of uLE (I would have to load some older ones to pinpoint some versions) but they used to display on the FTP side the following folders off the bat after pressing PS2NET from a shortcut on uLE's first page.

```
hdd
mass
mc
pfs
```
**NOTE**: The list below was done on PHAT Model -- see this tutorial as I provide screenshots of that setup using FlashFXP: http://www.ps2-home.com/forum/viewtopic.php?f=16&t=315

Then this changed when I had started this ticket issue that **mass** was no longer appearing on my SLIM.  It was only showing the **mc** folder and that was it.

After that, version that I listed above, you then made some changes and the **mass** folder was restored.  So currently with the most current revision of wLE it shows only the following folders (on a SLIM) via FTP:

```
mass
mc
```

So when you said that **_it was always like_** that earlier in this ticket, well, that is not what I recall with my FTP experience.  Unless you meant that FTP used to display all possible folders, but then you changed it in order to please some people complaining that they didn't want uLE to run the HDD as soon as it was launched?  So please clarify that for me?

As for trying to please everyone, I totally understand you.  No problem there.

Could this be possible?  Could a user setting be added to uLE's settings, so if the end-user wants the HDD to be running as soon as they launch uLE or at the very least PS2NET -- they can simple enable that feature  -- this way it's more of an option for those advanced users that use FTP?

Just a thought...

**Comment by sp193** [comment]
The behaviour changed between revisions to LaunchELF, through customizations not only by me, but by @AKuHAK. But I remember that it would not know of the "hdd" device by default because the FTP module gets its device list by stealing it from iomanX - which will not have the "hdd" device added until the HDD modules are loaded.
I also remember this being mentioned by dlanor, on psx-scene.

At some point, LaunchELF was always loading the HDD modules. Then it disappeared because I removed the loading of HDD modules unless the software was loaded, again by "popular demand".
I guess it should also work out, if LaunchELF was booted from the HDD unit by FHDB. Then the HDD modules would be loaded because LaunchELF was booted from the HDD.

By "original behaviour", I was referring to what **u**LaunchELF did. Whether it was wrong or right.
So you should refer to what the last true uLaunchELF version did, like v4.42d.

I don't use my PS2 anymore. In fact, it's been years since I actually played games on it for real.
Even if I am wrong about what LaunchELF, I won't commit to change it because I don't want to waste more time on things that don't make me happy.
